[package]
name = "aoc2025"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc2025"
path = "src/lib.rs"

[[bin]]
name = "aoc2025"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
